# Generated by Django 3.0 on 2019-12-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('Unique_Squirrel_ID', models.CharField(help_text='Unique squirrel ID', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Specific_Location', models.CharField(help_text='Specific location of squirrel inside central park', max_length=300)),
                ('Other_Activities', models.CharField(help_text='Other Activities', max_length=300)),
                ('Date', models.DateField(help_text='Date when the squirrel was observed')),
                ('SHIFT', models.CharField(choices=[('am', 'am'), ('pm', 'pm')], help_text='shit', max_length=2)),
                ('AGE', models.CharField(choices=[('Juvenile', 'Juvenile'), ('Adult', 'Adult'), ('?', '?')], help_text='Age of the squirrel', max_length=100, null=True)),
                ('PRIMARY_FUR_COLOR', models.CharField(choices=[('Grey', 'Grey'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Primary fur color of the squirrel', max_length=100, null=True)),
                ('LOCATION', models.CharField(choices=[('Above', 'Above'), ('Below', 'Below')], help_text='Locatrion of the squirrel', max_length=100, null=True)),
                ('Latitude', models.IntegerField(help_text='Latitude of the sighting', null=True)),
                ('Longitude', models.IntegerField(help_text='Longitude of the sighting', null=True)),
                ('Running', models.BooleanField(default=True, help_text='Running or not')),
                ('Chasing', models.BooleanField(default=True, help_text='Chasing or not')),
                ('Climbing', models.BooleanField(default=True, help_text='Climbing or not')),
                ('Eating', models.BooleanField(default=True, help_text='Eating or not')),
                ('Foraging', models.BooleanField(default=True, help_text='Foraging or not')),
                ('Kuks', models.BooleanField(default=True, help_text='Kuks boolean')),
                ('Quaas', models.BooleanField(default=True, help_text='Quaas boolean')),
                ('Moans', models.BooleanField(default=True, help_text='Moans boolean')),
                ('Tail_flags', models.BooleanField(default=True, help_text='Tail flags boolean')),
                ('Tail_twitches', models.BooleanField(default=True, help_text='Tail twitches or not')),
            ],
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
