# Generated by Django 2.2.7 on 2019-12-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0002_auto_20191204_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='fields',
            name='Approaches',
            field=models.BooleanField(blank=True, default=True, help_text='tick if it approaches you'),
        ),
        migrations.AddField(
            model_name='fields',
            name='Indifferent',
            field=models.BooleanField(blank=True, default=True, help_text='tick if it is indifferent to your presence'),
        ),
        migrations.AddField(
            model_name='fields',
            name='Runs_from',
            field=models.BooleanField(blank=True, default=True, help_text='tick if it starts running away from you'),
        ),
        migrations.AlterField(
            model_name='fields',
            name='AGE',
            field=models.CharField(blank=True, choices=[('Juvenile', 'Juvenile'), ('Adult', 'Adult'), ('?', '?')], help_text='how old do you think the squirrel might be?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Chasing',
            field=models.BooleanField(blank=True, default=True, help_text='tick if it is chasing you'),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Climbing',
            field=models.BooleanField(blank=True, default=True, help_text='tick if it is climbing up something'),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Date',
            field=models.DateField(blank=True, help_text="input today's date"),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Eating',
            field=models.BooleanField(blank=True, default=True, help_text='tick if it is eating something'),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Foraging',
            field=models.BooleanField(blank=True, default=True, help_text='tick if it is foraging'),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Kuks',
            field=models.BooleanField(blank=True, default=True, help_text='tick if you hear kuks'),
        ),
        migrations.AlterField(
            model_name='fields',
            name='LOCATION',
            field=models.CharField(blank=True, choices=[('Above', 'Above'), ('Below', 'Below')], help_text='what is your location', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Latitude',
            field=models.FloatField(blank=True, help_text='input the latitude of the sighting', null=True),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Longitude',
            field=models.FloatField(blank=True, help_text='input the longitude of the sighting', null=True),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Moans',
            field=models.BooleanField(blank=True, default=True, help_text='tick if you hear moans ;)'),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Other_Activities',
            field=models.CharField(blank=True, help_text='Other Activities', max_length=300),
        ),
        migrations.AlterField(
            model_name='fields',
            name='PRIMARY_FUR_COLOR',
            field=models.CharField(blank=True, choices=[('Grey', 'Grey'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='choose its colour', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Quaas',
            field=models.BooleanField(blank=True, default=True, help_text='tick if you hear quaas'),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Running',
            field=models.BooleanField(blank=True, default=True, help_text='tick if it is running'),
        ),
        migrations.AlterField(
            model_name='fields',
            name='SHIFT',
            field=models.CharField(blank=True, choices=[('am', 'am'), ('pm', 'pm')], help_text='choose if it was day or night', max_length=2),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Specific_Location',
            field=models.CharField(blank=True, help_text='describe its specific location', max_length=300),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Tail_flags',
            field=models.BooleanField(blank=True, default=True, help_text='tick if you see its tail flag'),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Tail_twitches',
            field=models.BooleanField(blank=True, default=True, help_text='tick if you see its tail twitch'),
        ),
        migrations.AlterField(
            model_name='fields',
            name='Unique_Squirrel_ID',
            field=models.CharField(default=None, help_text='input a unique id', max_length=100, primary_key=True, serialize=False),
        ),
    ]
